### ISSUE TITLE
clarify "slice" and "component"

### ISSUE THREAD

**Issue by monkeypants** [codeontap/codeontap#1]
I've heard these words used in the context of our stack, but am not clear on their meaning.

Please explicitly define them (or state that they are non-preferred aliases for some other phrase we have chosen to favour)

**Comment by roleyfoley** [comment]
slice has now been removed from the codeontap architecture and component has now considered the unit of a deployable unit which performs a specific function ( load balancer, container, lambda function etc) 

This is defined in our reference guide ( https://codeontap.readthedocs.io/en/stable/reference/cmdb-reference/ )
