### ISSUE TITLE
Add Release Promotion, Hotfix Preparation

### ISSUE THREAD

**Issue by ml019** [codeontap/codeontap#2]
Add the concept of "promotion" of a release into the current segment that has been accepted in a lower "PROMOTION" segment - typically the previous one.

A promotion will bring across all the application slice build references from the lower segment, and confirm that there are accepted images for all of them in the lower segment. It will not offer any override on the build references used.

Add the concept of a "hot fix" release. Hot fix preparation will operate in the same way as preparing a release in that it will accept and verify code tags against code repos, but will source images from a "HOTFIX" segment. 

Promotion will be the normal way to move releases through environments. A new release identifier will be created for the current segment since it also captures the state of settings and credentials.

Hot fix preparation will be used in higher environments that would normally use release promotion as the way new releases are created.

By default, the previous segment will be determined by looking at the environment of the current segment, and since there is a fixed set of these, using some environment masterData to define the promotion and hotfix relationships. 

The masterData will also capture the expected tag format for each segment when checking for existing build images. In this way the current prepareRelease job should be reusable for both prepareRelease and prepareHotFix jobs.

Default hotfix release tags will start with an "h" rather than a "r", so they are clearly identifiable in the config and infrastructure repos.

**Comment by roleyfoley** [comment]
Release preparation and deployment is now available in codeontap and supports the idea of promotion between environments.
