### ISSUE TITLE
Codeontap User Documenation site

### ISSUE THREAD

**Issue by roleyfoley** [codeontap/codeontap#22]
Create a codeontap user documentation site aimed at devops teams who would like to use codeontap as a product

**Comment by adamkerz** [comment]
It would be nice if this was able to be automatically deployed to an s3, sitting beside the infradocs stuff.

**Comment by monkeypants** [comment]
What slice of this could be done soon? I'd like to see something simple that could be improved over time as  we learn things.

**Comment by roleyfoley** [comment]
The Codeontap Project documentation site is now available here 
https://codeontap.readthedocs.io/en/stable/

Which aims to cover off a user guide of how to specifically use codeontap. I think we can call the setup of the site as completed. Will create separate tickets for integration with our other services
